import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});
const FugazOne = localFont({
  src: './fonts/FugazOne-Regular.woff',
  variable: '--font-fugaz-one',
  weight: '100 400',
});

export const metadata: Metadata = {
  title: 'The Note',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${FugazOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
